// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbstdmbeocrszmnmxuqa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFic3RkbWJlb2Nyc3ptbm14dXFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MzExNzcsImV4cCI6MjA1OTAwNzE3N30.zP_hR7AP4W4oLIvyd8HifyGJQrHJ_rI4TJdqrggR-l0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);