// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qpkrueienvzffvxunarb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwa3J1ZWllbnZ6ZmZ2eHVuYXJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1NTM1OTIsImV4cCI6MjA1NzEyOTU5Mn0.82VEzAm7_v5hOLc5XQDmnVfExthcN58Mb4hxQxf8K-E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);